# Generated by Django 5.0.6 on 2024-06-25 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_remove_user_created_on_post_created_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="second_name",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="twitter.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
