# Generated by Django 5.0.6 on 2024-06-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "twitter",
            "0004_rename_second_name_user_last_name_remove_user_posts_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_name",
            new_name="password",
        ),
    ]
